name: ACT issue templates

on:
  workflow_dispatch:

  issues:
    types:
      - opened

jobs:
  manual_templates_update:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: manual_templates_update
    uses: equinor/ops-py/.github/workflows/act_issue_templates.yml@main
    with:
      team_alias: act
      use_remote: true

  issue_create:
    if: ${{ github.event_name == 'issues' }}
    name: issue_create
    uses: equinor/ops-py/.github/workflows/act_issue_templates.yml@main
    with:
      team_alias: act